name: Blog post workflow
on:
  schedule:
    - cron: "0 15 * * *"

jobs:
  pull_blog_rss:
    name: Update with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://blog.beavernotes.com/feed.xml
          count: 3
      - name: Commit file changes
        run: |
          git config --global user.name "${{ secrets.MY_USERNAME }}"
          git config --global user.email "${{ secrets.MY_EMAIL }}"
          git add .
          git diff --quiet --cached || git commit -m "Update README"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
